[tool.poetry]
name = "lanhackbackend"
version = "0.1.0"
description = ""
authors = ["Isaac <the456gamer@the456gamer.dev>"]
readme = "README.md"
packages = [{include = "lanhackbackend"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
uvicorn = "^0.24.0.post1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
